project:
  type: website
  resources:
  - CNAME

website:
  title: janf
  site-url: https://janf.cc
  description: janf.cc
  favicon: images/janftxt_favicon.png
  search: 
    location: sidebar
    type: overlay
    keyboard-shortcut: [" "]
  sidebar:
    style: docked
    contents:
      - text: "Blog"
        file: blog.qmd
      - text: "Notes"
        file: notes.qmd
      - text: "About"
        file: about.qmd
    
format:
  html:
    theme: simplex
    css: styles.css



