project:
  type: website

website:
  title: "janf"
  site-url: https://janf.cc
  search: true
  navbar:
    left:
      - text: "Notes"
        file: notes.qmd
      - text: "About"
        file: about.qmd
    right:
      - icon: github
        href: https://github.com/janfdev
      - icon: twitter
        href: https://twitter.com/janfdev
    
format:
  html:
    theme: simplex
    css: styles.css



