project:
  type: website

website:
  title: "janf"
  search: true
  navbar:
    left:
      - text: "Notes"
        file: notes.qmd
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/
    
format:
  html:
    theme: simplex
    css: styles.css



