project:
  type: website
  resources:
  - CNAME

website:
  title: "janf"
  site-url: https://janf.cc
  description: "janf.cc"
  search: true
  navbar:
    left:
      - text: "Blog"
        file: blog.qmd
      - text: "Notes"
        file: notes.qmd
      - text: "About"
        file: about.qmd
    right:
      - icon: github
        href: https://github.com/xjanfcc
      - icon: twitter
      href: https://twitter.com/xjanfcc
    
format:
  html:
    theme: simplex
    css: styles.css



